### ISSUE TITLE
Closing TODOs

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#447]
As of this writing, https://greenelab.github.io/deep-review/ shows 18 remaining TODOs.  I'm skipping those that I can work on myself or have open pull requests to address them.

For the rest, can the following contributors please submit a small pull request to fix the issue or confirm we can remove the TODO:
- [x] @traversc: Discrimination and "right to an explanation" laws section, `TODO: @traversc citation needed`
- [x] @agapow: Promoters, enhancers, and related epigenomic tasks section.  Do we want to work on synchronizing TF binding and epigenomics?  We are so close to submitting that I'm hesitant to make major changes.  There is also a TODO about interaction prediction that you or me can address with a line or two.
- [x] @blengerich: Categorizing patients for clinical decision making section, `TODO: could really use some references for following paragraph`.  I believe you wrote the first draft of this paragraph.  Do you have any relevant references we can use? (#478)
- [x] Four TODOs in interpretation section of discussion
- [x] Acknowledgements section (#433)
- [x] Describe author ordering in Methods (#508)
- [x] Intro to deep learning (#491 #507)
- [x] CVPR17 dataset link (#483)
- [x] `tag:Abramoff2016_dr` DOI (#492)

**Comment by agapow** [comment]
I'd leave as is (promoters et al.) It's seems like a good idea, but not an essential one and I'm on conference at the moment and thus short on time and not in the best working circumstances.

**Comment by agitter** [comment]
Thanks @agapow, I'll leave it.  I'll make a pull request to purge these TODOs.

**Comment by agitter** [comment]
@akundaje We're planning to submit this review Wednesday.  Will you have time to look at the four TODOs in the interpretation section today?

**Comment by dhimmel** [comment]
@agitter you may find the GitHub markdown task list feature useful for your list above:

```md
- [x] task 1 (complete)
- [ ] task 2 (incomplete)
```

- [x] task 1 (complete)
- [ ] task 2 (incomplete)

**Comment by agitter** [comment]
@dhimmel I've used that before but was lazy here.  I updated the original post because I like how it tracks progress in the issue list.

**Comment by agitter** [comment]
All TODOS have been removed or have pending pull requests to remove them.
