### ISSUE TITLE
Steps toward submission

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#467]
I'm outlining the steps that @cgreene and I will take toward submitting this manuscript to bioRxiv and  *Journal of the Royal Society Interface* after our deadline for new contributions and author approval (noon Eastern on May 17) passes:
- [x] Final proofreading
- [x] Edit acronyms and terminology for consistency (#345 #391)
- [x] Remove or address the remaining TODOs (#447)
- [x] Add all contributors to the author list (#446) if they approved the manuscript or the acknowledgements (#433) if they did not
- [x] Order the authors and add to the manuscript (#369 #508)
- [x] Add a funding statement (#502)
- [x] Improve the handling of URLs and arXiv ids in references, manual JSON corrections (#381)
- [x] Check the references for preprint and published versions of the same manuscript (#474)
- [x] TF and enhancer section updates (#473 #475)
- [x] Paper title (#496)
- [x] Conflict of interest statement (#518)

**Comment by cgreene** [comment]
@dhimmel : I'm trying to get a PDF built and I get:

```
cgreene@casey-greenelab:~/workspace/deep-review/build$ conda env create --file environment.yml
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: .
Error: Packages missing in current linux-64 channels: 
  - bioconda::wkhtmltopdf 0.12.3*
  - conda-forge::pandoc 1.19.2*
cgreene@casey-greenelab:~/workspace/deep-review/build$ source activate deep-review
could not find environment: deep-review
cgreene@casey-greenelab:~/workspace/deep-review/build$ 
```

**Comment by cgreene** [comment]
Ok - I tracked it down via gh-pages. I'm good to go @dhimmel  :)

**Comment by dhimmel** [comment]
@cgreene it looks like there are multiple errors. First, the `missing in current linux-64 channels`. Not sure why this would happen (since it works on Travis CI). Second, it should be `source activate deepreview` not `source activate deep-review`.

**Comment by agitter** [comment]
Using the reference numbers from version 7cde21b22991bf573091c9c5654be4b9be52c5ec I found three possible pairs of redundant references.  I can fix it myself, but not immediately.
- Beaulieu-Jones et al: 58 and 83
- McMahan et al: 119 and 120
- Shrikumar et al: 168 and 332 (noted in #469)

**Comment by dhimmel** [comment]
> I can fix it myself, but not immediately.

@agitter why don't you go ahead and fix these. Let me know if you run into any troubles.

**Comment by agitter** [comment]
@dhimmel Sure, I can.  I have meetings the rest of the day and will take care of it tonight.

**Comment by agitter** [comment]
@cgreene I've proofread all sections except `03_categorize.md`.  I'll wait until we merge #483 and then re-read it.

**Comment by cgreene** [comment]
My proofread comments are complete 👍

**Comment by agitter** [comment]
After we merge #497, I'll go through all of the sections and work on consistency issues like abbreviations, hyphens vs. dashes, etc.

**Comment by agitter** [comment]
Everything is ready!
